show_downloads: false
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Favian Ioel P.
email: favianioel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'm awesome , e'nuf said.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://favianioel.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  favianioel
remote_theme: daattali/beautiful-jekyll@6.0.1

# Build settings
markdown: kramdown
